---
name: Configure OSUOSL CA Certificate
description: >-
  In July 2026, OSUOSL switched to using a TLS Certificate with a trust
  chain rooted at "emSign Root CA - G1". This poses a problem as the
  AWS CLI currently vendors an old CA bundle generated in 2018 that does
  not include this CA cert:

    https://github.com/aws/aws-cli/issues/10389

  This action downloads the latest Mozilla CA bundle, writes it out to a file
  under $RUNNER_TEMP, and then sets the path to that file in the AWS_CA_BUNDLE
  environment variable. The AWS CLI will read certificates from this variable,
  unless overriden by something like the "--ca-bundle" CLI flag.

runs:
  using: composite
  steps:
    - name: Set Up OSUOSL CA Certificate
      shell: bash
      env:
        SHELLOPTS: igncr
      run: |
        # Replace any backslashes with forward slashes so that a Windows path
        # is usable from both POSIX and WIN32 contexts.
        osuosl_ca="${RUNNER_TEMP//\\//}/osuosl-ca.pem"

        printf 'Downloading Mozilla CA bundle to: %s\n' "${osuosl_ca}"

        curl -sSL https://curl.se/ca/cacert.pem -o "${osuosl_ca}"

        printf 'AWS_CA_BUNDLE=%s' "${osuosl_ca}" >>$GITHUB_ENV
